# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicedemo-deployment
  labels:
    app: servicedemo-sb
spec:
  replicas: 1 # Puedes ajustar el número de réplicas
  selector:
    matchLabels:
      app: servicedemo-sb
  template:
    metadata:
      labels:
        app: servicedemo-sb
    spec:
      containers:
        - name: servicedemo-container
          # ¡Reemplaza con el nombre de la imagen que has subido!
          image: wilmeraguilar/servicedemo-sb:1.1
          ports:
            - containerPort: 8080 # Puerto por defecto de Spring Boot